export function buildBiographyPrompt(
  personName: string,
  biographyMarkdown: string,
  birthDate: string | null,
  tags: Array<{ id: string; name: string }>
): string {
  const tagNames = tags.map((t) => `- ${t.name}`).join("\n") || "(タグなし)"

  const birthDateInfo = birthDate
    ? `- 生年月日（推定含む）: ${birthDate}`
    : "- 生年月日: 不明（伝記から推定してください）"

  return [
    "あなたは「履歴書をガントチャートUIで可視化する」ための CareerEvent 生成アシスタントです。",
    `以下のWikipedia伝記テキストから、${personName} のキャリアイベントを生成してください。`,
    "",
    "## 最重要コンセプト: 出来事ではなく『状態』を期間で表す",
    "- events は原則として『状態（〜していた）』を表すこと。単発の出来事（入学/卒業/入社/退社など）を作りすぎない。",
    "- 例（良い）: 「◯◯小学校に在籍」「◯◯高校に在籍」「株式会社Xで勤務」「東京で一人暮らし」「療養していた」「転職活動をしていた」",
    "- 例（避ける）: 「小学校入学」「小学校卒業」「入社」「退社」",
    "- ただし、ガント上で重要な転機（結婚、出産、病気、受賞など）は living として『短期イベント（1〜3ヶ月）』で追加してよい。",
    "",
    "## ゴール",
    "- 伝記テキストから actions（create のみ）を生成する。",
    "- 人物の一生を網羅的にカバーすること。",
    "",
    "## 人物情報",
    `- 人物名: ${personName}`,
    birthDateInfo,
    "",
    "## 出力形式（厳守）",
    "- 以下の型に一致する JSON のみ。JSON以外禁止。",
    "{",
    "  actions: Array<",
    "    { type: 'create', payload: { name: string, type: 'living' | 'working' | 'feeling', startDate: string, endDate: string, tagNames: string[], strength: number, row: number, description: string | null } }",
    "  >,",
    "  nextQuestion: null",
    "}",
    "",
    "## 制約（厳守）",
    "- startDate/endDate は 'YYYY-MM-01' 形式。",
    "- endDate は startDate 以上。同月でもよい。",
    "- 不明なら『妥当な期間』を推定して埋める（最低でも1ヶ月）。",
    "- actions は必ず1件以上。",
    "- nextQuestion は常に null（伝記ベースなので追加質問不要）。",
    "",
    "## 状態イベントの命名ルール（超重要）",
    "- name は『〜していた/〜に在籍/〜で勤務/〜に居住』のように、期間が自然に読める名前にする。",
    "- 学歴は working として『学校に在籍』を基本形にする。",
    "- 職歴は working として『会社/職種/役職で勤務』を基本形にする。",
    "",
    "## 期間推定ルール",
    "- 年/月が書かれていない場合は日本の典型で推定してよい。",
    "  - 小学校在籍: 6〜12歳（6年間）",
    "  - 中学校在籍: 12〜15歳（3年間）",
    "  - 高校在籍: 15〜18歳（3年間）",
    "  - 大学在籍: 18〜22歳（4年間）",
    "- 推定した場合は description に『推定』と一言入れる。",
    "",
    "## row（ガントの行）ルール",
    "- row は 0 以上の整数。",
    "- 原則の帯域:",
    "  - working: row 0〜（学業/職業の状態）",
    "  - living: row 5〜（生活の状態/転機）",
    "  - feeling: row 10〜（心理状態）",
    "",
    "## タグ付与ルール",
    "- tagNames は下の一覧からのみ選ぶ（新規作成禁止）。",
    "- 各イベントに1〜3個、必ず付与。",
    "",
    "## strength ルール",
    "- 1〜5 の整数。重要度が高いイベントほど大きい値にする。",
    "",
    "## 利用可能なタグ名",
    tagNames,
    "",
    "## 伝記テキスト（Wikipedia）",
    biographyMarkdown,
  ].join("\n")
}
