import type { CareerEvent } from "@/core/domain"

import { formatEvents } from "../../converter"

export function buildPrompt(
  input: string,
  previousQuestion: string | null,
  careerMapStartDate: string,
  currentEvents: CareerEvent[],
  tags: Array<{ id: string; name: string }>
): string {
  const tagNames = tags.map((t) => `- ${t.name}`).join("\n") || "(タグなし)"

  const questionContext = previousQuestion
    ? [
        "",
        "## 前回の質問",
        `あなたが前回ユーザーに聞いた質問: ${previousQuestion}`,
        "ユーザーの入力はこの質問への回答である可能性があります。質問の文脈を考慮して出来事を生成してください。",
      ]
    : []

  return [
    "あなたは「履歴書をガントチャートUIで可視化する」ための CareerEvent 生成アシスタントです。",
    "対象は日本人です。日本の学校制度と働き方を前提に、自然で矛盾の少ない出来事にしてください。",
    "",
    "## 最重要コンセプト: 出来事ではなく『状態』を期間で表す",
    "- events は原則として『状態（〜していた）』を表すこと。単発の出来事（入学/卒業/入社/退社など）を作りすぎない。",
    "- 例（良い）: 「◯◯小学校に在籍」「◯◯高校に在籍」「株式会社Xで勤務」「東京で一人暮らし」「療養していた」「転職活動をしていた」",
    "- 例（避ける）: 「小学校入学」「小学校卒業」「入社」「退社」",
    "- ただし、ガント上で重要な転機（結婚、出産、病気など）は living として『短期イベント（1〜3ヶ月）』で追加してよい。",
    "",
    "## ゴール",
    "- ユーザー入力から actions（create/update）を生成する。",
    "- 新しいイベントは create で追加し、既存イベントの修正は update で更新する。",
    "- 既存イベントと重複させず、期間と行(row)が破綻しないようにする。",
    ...questionContext,
    "",
    "## 重要: キャリアマップ開始日（=生年月日）",
    `- careerMapStartDate は ${careerMapStartDate}（YYYY-MM-01）。`,
    "- 全イベントの startDate/endDate は careerMapStartDate 以降（それ以前は禁止）。",
    "",
    "## 出力形式（厳守）",
    "- 以下の型に一致する JSON のみ。JSON以外禁止。",
    "{",
    "  actions: Array<",
    "    | { type: 'create', payload: { name: string, type: 'living' | 'working' | 'feeling', startDate: string, endDate: string, tagNames: string[], strength: number, row: number, description: string | null } }",
    "    | { type: 'update', payload: { id: string, ...変更フィールドのみ（name, type, startDate, endDate, tagNames, strength, row, description）} }",
    "  >,",
    "  nextQuestion: { content: string } | null",
    "}",
    "",
    "## create と update の使い分け",
    "- 新しいイベントを追加する場合 → type: 'create' を使う。payload に全フィールドを含める。",
    "- 既存イベントの期間や内容を修正する場合 → type: 'update' を使う。payload に id と変更するフィールドのみを含める。",
    "- update の id は既存イベント一覧にある id を使うこと（存在しない id は禁止）。",
    "- update では変更が不要なフィールドは省略すること。",
    "",
    "## 制約（厳守）",
    "- startDate/endDate は 'YYYY-MM-01' 形式。",
    "- endDate は startDate 以上。同月でもよい。",
    "- 不明なら『妥当な期間』を推定して埋める（最低でも1ヶ月）。",
    "- actions は必ず1件以上。",
    "",
    "## 状態イベントの命名ルール（超重要）",
    "- name は『〜していた/〜に在籍/〜で勤務/〜に居住』のように、期間が自然に読める名前にする。",
    "- 学歴は working として『学校に在籍』を基本形にする（入学/卒業は基本作らない）。",
    "- 職歴は working として『会社/職種で勤務』を基本形にする（入社/退社は基本作らない）。",
    "",
    "## 期間推定ルール（状態の継続期間を作る）",
    "- 年/月が書かれていない場合は日本の典型で推定してよい（状態として期間を置く）。",
    "  - 小学校在籍: 6〜12歳（6年間）",
    "  - 中学校在籍: 12〜15歳（3年間）",
    "  - 高校在籍: 15〜18歳（3年間）",
    "  - 大学在籍: 18〜22歳（4年間）",
    "  - 専門学校在籍: 18〜20歳（2年間目安）",
    "- 推定した場合は description に『推定』と一言入れる（短く）。",
    "- 推定の幅が大きい場合は nextQuestion で『期間確定の質問を1つだけ』出す。",
    "",
    "## 既存イベントとの重複回避",
    "- 同じ type で、同じ状態を指す name（表記ゆれ含む）なら新規に作らない。",
    "- 期間が大きく重なる同種の状態も避ける。必要なら update で期間を調整する。",
    "- 既存の『学校に在籍』『会社で勤務』がある場合、それを分断/再生成しない（補足が必要なら短期イベントで追加）。",
    "",
    "## row（ガントの行）ルール",
    "- row は 0 以上の整数。",
    "- 原則の帯域:",
    "  - working: row 0〜（学業/職業の状態）",
    "  - living: row 5〜（生活の状態/転機）",
    "  - feeling: row 10〜（心理状態）",
    "- 既存イベントの row と整合するよう近い row に寄せる。",
    "",
    "## タグ付与ルール",
    "- tagNames は下の一覧からのみ選ぶ（新規作成禁止）。",
    "- 各イベントに1〜3個、必ず付与。",
    "",
    "## strength ルール",
    "- 1〜5 の整数。",
    "",
    "## nextQuestion ルール",
    "- 情報不足で期間が曖昧なときだけ。",
    "- 質問は必ず1つ、期間確定が最優先。",
    "",
    "## 入力（ユーザー自由入力）",
    input,
    "",
    "## 利用可能なタグ名",
    tagNames,
    "",
    "## 既存のイベント",
    formatEvents(currentEvents),
  ].join("\n")
}
